-- Generate a couple of departments
INSERT INTO DEPARTMENT(DEPARTMENT_ID, NAME, FLOOR)
    VALUES (1, 'Human Resource', 1);
INSERT INTO DEPARTMENT(DEPARTMENT_ID, NAME, FLOOR)
    VALUES (2, 'Building Services', 2);
INSERT INTO DEPARTMENT(DEPARTMENT_ID, NAME, FLOOR)
    VALUES (3, 'Information Technology', 3);
INSERT INTO DEPARTMENT(DEPARTMENT_ID, NAME, FLOOR)
    VALUES (4, 'Legal', 4);
INSERT INTO DEPARTMENT(DEPARTMENT_ID, NAME, FLOOR)
    VALUES (5, 'Public Affairs', 5);
INSERT INTO DEPARTMENT(DEPARTMENT_ID, NAME, FLOOR)
    VALUES (6, 'Finance', 6);
INSERT INTO DEPARTMENT(DEPARTMENT_ID, NAME, FLOOR)
    VALUES (7, 'Security', 7);

INSERT INTO PURCHASE_ORDER (PURCHASE_ORDER_ID, SUBMIT_DATE, DESCRIPTION, FK_DEPARTMENT_ID, PURCHASER_NAME)
    VALUES (1, CURRENT_DATE, 'This is a description', 3, 'Fred Sanford');
INSERT INTO PURCHASE_ORDER_LINE_ITEM (PO_LINE_ITEM_ID, FK_PURCHASE_ORDER_ID, ITEM_DESCRIPTION, QUANTITY, UNIT_PRICE, TOTAL_PRICE)
    VALUES(1, 1, 'Cocoa Puffs', 2, 1.50, 3.00);


