    -- Dropping tables initially in case they exist
    DROP TABLE IF EXISTS DEPARTMENT;
    DROP TABLE IF EXISTS PURCHASE_ORDER;
    DROP TABLE IF EXISTS PURCHASE_ORDER_LINE_ITEM;

    -- Drop the Employee Sequence if it exists
    DROP SEQUENCE IF EXISTS DEPT_ID_SEQ;
    DROP SEQUENCE IF EXISTS PURCHASE_ORDER_ID_SEQ;
    DROP SEQUENCE IF EXISTS PO_LINE_ITEM_ID_SEQ;

    CREATE TABLE DEPARTMENT (
        DEPARTMENT_ID BIGINT NOT NULL,
        NAME VARCHAR(50),
        FLOOR INTEGER,
        PRIMARY KEY (DEPARTMENT_ID)
    );

    CREATE TABLE PURCHASE_ORDER (
        PURCHASE_ORDER_ID BIGINT NOT NULL,
        SUBMIT_DATE DATE,
        DESCRIPTION VARCHAR(250),
        FK_DEPARTMENT_ID BIGINT,
        PURCHASER_NAME VARCHAR(50),
        PRIMARY KEY (PURCHASE_ORDER_ID)
    );

    CREATE TABLE PURCHASE_ORDER_LINE_ITEM (
        PO_LINE_ITEM_ID BIGINT NOT NULL,
        FK_PURCHASE_ORDER_ID BIGINT NOT NULL,
        ITEM_DESCRIPTION VARCHAR(100),
        QUANTITY INTEGER,
        UNIT_PRICE NUMERIC(20, 2),
        TOTAL_PRICE NUMERIC(20, 2),
        PRIMARY KEY (PO_LINE_ITEM_ID)
    );

    --  Creating the sequences for primary key creation
    CREATE SEQUENCE DEPT_ID_SEQ START 100 INCREMENT 1 MINVALUE 100 OWNED BY DEPARTMENT.DEPARTMENT_ID;
    CREATE SEQUENCE PURCHASE_ORDER_ID_SEQ START 100 INCREMENT 1 MINVALUE 100 OWNED BY PURCHASE_ORDER.PURCHASE_ORDER_ID;
    CREATE SEQUENCE PO_LINE_ITEM_ID_SEQ START 100 INCREMENT 1 MINVALUE 100 OWNED BY PURCHASE_ORDER_LINE_ITEM.PO_LINE_ITEM_ID;

    ALTER TABLE PURCHASE_ORDER_LINE_ITEM ADD CONSTRAINT FK_PURCHASE_LINE_ITEM_PO_CONSTRAINT
    FOREIGN KEY (FK_PURCHASE_ORDER_ID)
    REFERENCES PURCHASE_ORDER (PURCHASE_ORDER_ID);

    ALTER TABLE PURCHASE_ORDER ADD CONSTRAINT FK_PURCHASE_ORDER_DEPARTMENT
    FOREIGN KEY (FK_DEPARTMENT_ID)
    REFERENCES DEPARTMENT (DEPARTMENT_ID);

    ALTER TABLE department ALTER COLUMN DEPARTMENT_ID SET DEFAULT nextval('DEPT_ID_SEQ');
    ALTER TABLE purchase_order ALTER COLUMN PURCHASE_ORDER_ID SET DEFAULT nextval('PURCHASE_ORDER_ID_SEQ');
    ALTER TABLE purchase_order_line_item ALTER COLUMN PO_LINE_ITEM_ID SET DEFAULT nextval('PO_LINE_ITEM_ID_SEQ');

    GRANT INSERT, SELECT, UPDATE, DELETE
    ON TABLE DEPARTMENT
    TO "POSYSTEMAPPROLE";

    GRANT INSERT, SELECT, UPDATE, DELETE
    ON TABLE PURCHASE_ORDER
    TO "POSYSTEMAPPROLE";

    GRANT INSERT, SELECT, UPDATE, DELETE
    ON TABLE PURCHASE_ORDER_LINE_ITEM
    TO "POSYSTEMAPPROLE";

    GRANT ALL ON SEQUENCE DEPT_ID_SEQ TO "POSYSTEMAPPROLE";
    GRANT USAGE ON SEQUENCE PURCHASE_ORDER_ID_SEQ TO "POSYSTEMAPPROLE";
    GRANT ALL ON SEQUENCE PO_LINE_ITEM_ID_SEQ TO "POSYSTEMAPPROLE";
