server:
  port: 8081
  servlet:
    context-path: /purchaseordersystem
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:PO_SYSTEM;DB_CLOSE_DELAY=-1
    username: sa
  flyway:
    baselineOnMigrate: true
    baselineDescription: "FLYWAY-BASELINE"
    enabled: true
    locations: "classpath:db/migration/h2"
    outOfOrder: false
    validateOnMigrate: true
  h2:
    console:
      enabled: true
      path: /myh2
  jmx:
    default-domain: /purchaseordersystem
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
    open-in-view: true
    properties:
      hibernate:
        batch_versioned_data: true
        generate_statistics: true
        order_inserts: true
        order_updates: true
        jdbc:
          batch_size: 250
        default_schema: PURCHASE_ORDER_SYSTEM_SCHEMA
        show_sql: true
    show-sql: true
  main:
    allow-bean-definition-overriding: true
  # The following property used to fix Swagger Issues with Spring Boot 2.6
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
---

spring:
  config:
    activate:
      on-profile:
        - postgresql-profile #"This will be a Docker PostgreSQL Database"
  datasource:
    driver-class-name: "org.postgresql.Driver"
    url: "jdbc:postgresql://localhost:5432/purchase_order_system_db"
    username: "PO_SYSTEM_APP_USER"
    password: "mynonsecretpassw0rd"
  flyway:
    create-schemas: false
    default-schema: purchase_order_system_schema
    locations: "classpath:db/migration/postgresql"
    mixed: true
    password: "mysecret"
    schemas: purchase_order_system_schema
    url: "jdbc:postgresql://localhost:5432/purchase_order_system_db"
    user: "PO_SYSTEM_OWNER_USER"
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    properties:
      hibernate:
        default_schema: purchase_order_system_schema
        batch_versioned_data: true
        generate_statistics: true
        order_inserts: true
        order_updates: true
        jdbc:
          batch_size: 1000
          lob:
            non_contextual_creation: true
        dialect: "org.hibernate.dialect.PostgreSQL10Dialect"
        format_sql: true
        temp:
          use_jdbc_metadata_defaults: false
        sessions:
          events:
            log:
              LOG_QUERIES_SLOWER_THAN_MS: 10
    open-in-view: true
    show-sql: true

