#management:
#  endpoint:
#    flyway:
#      enabled: true
#  endpoints:
#    web:
#      exposure:
#        include: "*"
server:
  port: 8081
  servlet:
    context-path: /purchaseordersystem
spring:
  datasource:
    driver-class-name: org.h2.Driver
    platform: "h2"
    url: jdbc:h2:mem:PO_SYSTEM;DB_CLOSE_DELAY=-1
    username: sa
  flyway:
    baselineOnMigrate: true
    baselineDescription: "FLYWAY-BASELINE"
    enabled: true
    ignoreMissingMigrations: true
    locations: "classpath:db/migration/h2"
    outOfOrder: false
    validateOnMigrate: true
  h2:
    console:
      enabled: true
      path: /myh2
  jmx:
    default-domain: /purchaseordersystem
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
    open-in-view: true
    properties:
      hibernate:
        default_schema: PURCHASE_ORDER_SYSTEM_SCHEMA
  main:
    allow-bean-definition-overriding: true
  # The following property used to fix Swagger Issues with Spring Boot 2.6
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
---
