    DROP SCHEMA IF EXISTS PURCHASE_ORDER_SYSTEM_SCHEMA;

    CREATE SCHEMA IF NOT EXISTS PURCHASE_ORDER_SYSTEM_SCHEMA;
    SET SCHEMA PURCHASE_ORDER_SYSTEM_SCHEMA;

    CREATE SEQUENCE DEPT_ID_SEQ START WITH 100 INCREMENT BY 1;
    CREATE SEQUENCE PURCHASE_ORDER_ID_SEQ START WITH 100 INCREMENT BY 1;
    CREATE SEQUENCE PO_LINE_ITEM_ID_SEQ START WITH 100 INCREMENT BY 1;

    CREATE TABLE DEPARTMENT (
        DEPARTMENT_ID BIGINT DEFAULT NEXT VALUE FOR DEPT_ID_SEQ,
        NAME VARCHAR(50),
        FLOOR INTEGER,
        PRIMARY KEY (DEPARTMENT_ID)
    );

    CREATE TABLE PURCHASE_ORDER (
        PURCHASE_ORDER_ID BIGINT DEFAULT NEXT VALUE FOR PURCHASE_ORDER_ID_SEQ,
        SUBMIT_DATE DATE,
        DESCRIPTION VARCHAR(250),
        FK_DEPARTMENT_ID BIGINT,
        PURCHASER_NAME VARCHAR(50),
        PRIMARY KEY (PURCHASE_ORDER_ID)
    );

    CREATE TABLE PURCHASE_ORDER_LINE_ITEM (
        PO_LINE_ITEM_ID BIGINT DEFAULT NEXT VALUE FOR PO_LINE_ITEM_ID_SEQ,
        FK_PURCHASE_ORDER_ID BIGINT NOT NULL,
        ITEM_DESCRIPTION VARCHAR(100),
        QUANTITY INTEGER,
        UNIT_PRICE NUMERIC(20, 2),
        TOTAL_PRICE NUMERIC(20, 2),
        PRIMARY KEY (PO_LINE_ITEM_ID)
    );

    ALTER TABLE PURCHASE_ORDER_LINE_ITEM ADD CONSTRAINT FK_PURCHASE_LINE_ITEM_PO_CONSTRAINT
    FOREIGN KEY (FK_PURCHASE_ORDER_ID)
    REFERENCES PURCHASE_ORDER;

    ALTER TABLE PURCHASE_ORDER ADD CONSTRAINT FK_PURCHASE_ORDER_DEPARTMENT
    FOREIGN KEY (FK_DEPARTMENT_ID)
    REFERENCES DEPARTMENT;
