# Use postgres/example user/password credentials
version: '3.1'
services:
  db:
    image: postgres
    restart: always
    container_name: purchase-order-application-postgresql-img
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: mysecret
      POSTGRES_USER: postgres
      GDATA: /var/lib/postgresql/pgdata
